package ro.bb.tranzactii.model;

import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

@Getter
@Setter
public class Transaction {

    public long   localId         ;
    public String transactionId   ;
    public long   checksum        ;
    public String debtorAcct1     ;
    public String debtorAcct2     ;
    public String debtorAcct3     ;
    public String debtorAcct4     ;
    public String creditorAcct1   ;
    public String creditorAcct2   ;
    public String creditorAcct3   ;
    public String creditorAcct4   ;
    public BigDecimal amount;
    public long   numeric01       ;
    public long   numeric02       ;
    public long   numeric03       ;
    public long   numeric04       ;
    public long   numeric05       ;
    public long   numeric06       ;
    public long   numeric07       ;
    public long   numeric08       ;
    public long   numeric09       ;
    public long   numeric10       ;
    public long   numeric11       ;
    public long   numeric12       ;
    public long   numeric13       ;
    public long   numeric14       ;
    public long   numeric15       ;
    public long   numeric16       ;
    public long   numeric17       ;
    public long   numeric18       ;
    public long   numeric19       ;
    public long   numeric20       ;
    public long   numeric21       ;
    public long   numeric22       ;
    public long   numeric23       ;
    public long   numeric24       ;
    public long   numeric25       ;
    public long   numeric26       ;
    public long   numeric27       ;
    public long   numeric28       ;
    public long   numeric29       ;
    public long   numeric30       ;
    public long   numeric31       ;
    public long   numeric32       ;
    public long   numeric33       ;
    public long   numeric34       ;
    public long   numeric35       ;
    public long   numeric36       ;
    public long   numeric37       ;
    public long   numeric38       ;
    public long   numeric39       ;
    public long   numeric40       ;
    public long   numeric41       ;
    public long   numeric42       ;
    public long   numeric43       ;
    public long   numeric44       ;
    public long   numeric45       ;
    public long   numeric46       ;
    public long   numeric47       ;
    public long   numeric48       ;
    public long   numeric49       ;
    public long   numeric50       ;
    public long   numeric51       ;
    public long   numeric52       ;
    public long   numeric53       ;
    public long   numeric54       ;
    public String alphanr01       ;
    public String alphanr02       ;
    public String alphanr03       ;
    public String alphanr04       ;
    public String alphanr05       ;
    public String alphanr06       ;
    public String alphanr07       ;
    public String alphanr08       ;
    public String alphanr09       ;
    public String alphanr10       ;
    public String alphanr11       ;
    public String alphanr12       ;
    public String alphanr13       ;
    public String alphanr14       ;
    public String alphanr15       ;
    public String alphanr16       ;
    public String alphanr17       ;
    public String alphanr18       ;
    public String alphanr19       ;
    public String alphanr20       ;
    public String alphanr21       ;
    public String alphanr22       ;
    public String alphanr23       ;
    public String alphanr24       ;
    public String alphanr25       ;
    public String alphanr26       ;
    public String alphanr27       ;
    public String alphanr28       ;
    public String alphanr29       ;
    public String alphanr30       ;
    public String alphanr31       ;
    public String alphanr32       ;
    public String alphanr33       ;
    public String alphanr34       ;
    public String alphanr35       ;
    public String alphanr36       ;
    public String alphanr37       ;
    public String alphanr38       ;
    public String alphanr39       ;
    public String alphanr40       ;
    public String alphanr41       ;
    public String alphanr42       ;
    public String alphanr43       ;
    public String alphanr44       ;
    public String alphanr45       ;
    public String alphanr46       ;
    public String alphanr47       ;
    public String alphanr48       ;
    public String alphanr49       ;
    public String alphanr50       ;
    public String alphanr51       ;
    public String alphanr52       ;
    public String alphanr53       ;
    public String alphanr54       ;
    public OffsetDateTime operationTmstmp;
    public String additionalInfo  ;


    @Override
    public String toString() {
        return "Transaction " + transactionId + " (localId=" + localId + ", checksum " + checksum +")";
    }
}
