package ro.bb.tranzactii.repositories;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import ro.bb.tranzactii.model.Transaction;

import javax.sql.DataSource;
import java.util.HashMap;
import java.util.Map;

@Repository
public class TransactionTemplateRepository {

    private static final String INSERT_TRANSACTION_SQL = """
               INSERT INTO tranzactii
               ( local_id
               , transaction_id
               , checksum
               , debtor_acct1
               , debtor_acct2
               , debtor_acct3
               , debtor_acct4
               , creditor_acct1
               , creditor_acct2
               , creditor_acct3
               , creditor_acct4
               , amount
               , numeric01
               , numeric02
               , numeric03
               , numeric04
               , numeric05
               , numeric06
               , numeric07
               , numeric08
               , numeric09
               , numeric10
               , numeric11
               , numeric12
               , numeric13
               , numeric14
               , numeric15
               , numeric16
               , numeric17
               , numeric18
               , numeric19
               , numeric20
               , numeric21
               , numeric22
               , numeric23
               , numeric24
               , numeric25
               , numeric26
               , numeric27
               , numeric28
               , numeric29
               , numeric30
               , numeric31
               , numeric32
               , numeric33
               , numeric34
               , numeric35
               , numeric36
               , numeric37
               , numeric38
               , numeric39
               , numeric40
               , numeric41
               , numeric42
               , numeric43
               , numeric44
               , numeric45
               , numeric46
               , numeric47
               , numeric48
               , numeric49
               , numeric50
               , numeric51
               , numeric52
               , numeric53
               , numeric54
               , alphanr01
               , alphanr02
               , alphanr03
               , alphanr04
               , alphanr05
               , alphanr06
               , alphanr07
               , alphanr08
               , alphanr09
               , alphanr10
               , alphanr11
               , alphanr12
               , alphanr13
               , alphanr14
               , alphanr15
               , alphanr16
               , alphanr17
               , alphanr18
               , alphanr19
               , alphanr20
               , alphanr21
               , alphanr22
               , alphanr23
               , alphanr24
               , alphanr25
               , alphanr26
               , alphanr27
               , alphanr28
               , alphanr29
               , alphanr30
               , alphanr31
               , alphanr32
               , alphanr33
               , alphanr34
               , alphanr35
               , alphanr36
               , alphanr37
               , alphanr38
               , alphanr39
               , alphanr40
               , alphanr41
               , alphanr42
               , alphanr43
               , alphanr44
               , alphanr45
               , alphanr46
               , alphanr47
               , alphanr48
               , alphanr49
               , alphanr50
               , alphanr51
               , alphanr52
               , alphanr53
               , alphanr54
               , operation_tmstmp
               , additional_info
               )
               VALUES
               ( :localId
               , :transactionId
               , :checksum
               , :debtorAcct1
               , :debtorAcct2
               , :debtorAcct3
               , :debtorAcct4
               , :creditorAcct1
               , :creditorAcct2
               , :creditorAcct3
               , :creditorAcct4
               , :amount
               , :numeric01
               , :numeric02
               , :numeric03
               , :numeric04
               , :numeric05
               , :numeric06
               , :numeric07
               , :numeric08
               , :numeric09
               , :numeric10
               , :numeric11
               , :numeric12
               , :numeric13
               , :numeric14
               , :numeric15
               , :numeric16
               , :numeric17
               , :numeric18
               , :numeric19
               , :numeric20
               , :numeric21
               , :numeric22
               , :numeric23
               , :numeric24
               , :numeric25
               , :numeric26
               , :numeric27
               , :numeric28
               , :numeric29
               , :numeric30
               , :numeric31
               , :numeric32
               , :numeric33
               , :numeric34
               , :numeric35
               , :numeric36
               , :numeric37
               , :numeric38
               , :numeric39
               , :numeric40
               , :numeric41
               , :numeric42
               , :numeric43
               , :numeric44
               , :numeric45
               , :numeric46
               , :numeric47
               , :numeric48
               , :numeric49
               , :numeric50
               , :numeric51
               , :numeric52
               , :numeric53
               , :numeric54
               , :alphanr01
               , :alphanr02
               , :alphanr03
               , :alphanr04
               , :alphanr05
               , :alphanr06
               , :alphanr07
               , :alphanr08
               , :alphanr09
               , :alphanr10
               , :alphanr11
               , :alphanr12
               , :alphanr13
               , :alphanr14
               , :alphanr15
               , :alphanr16
               , :alphanr17
               , :alphanr18
               , :alphanr19
               , :alphanr20
               , :alphanr21
               , :alphanr22
               , :alphanr23
               , :alphanr24
               , :alphanr25
               , :alphanr26
               , :alphanr27
               , :alphanr28
               , :alphanr29
               , :alphanr30
               , :alphanr31
               , :alphanr32
               , :alphanr33
               , :alphanr34
               , :alphanr35
               , :alphanr36
               , :alphanr37
               , :alphanr38
               , :alphanr39
               , :alphanr40
               , :alphanr41
               , :alphanr42
               , :alphanr43
               , :alphanr44
               , :alphanr45
               , :alphanr46
               , :alphanr47
               , :alphanr48
               , :alphanr49
               , :alphanr50
               , :alphanr51
               , :alphanr52
               , :alphanr53
               , :alphanr54
               , :operationTmstmp
               , :additionalInfo
               )
            """;

    DataSource dataSource;
    NamedParameterJdbcTemplate template;

    @Autowired
    public TransactionTemplateRepository(@Qualifier("dataSource") DataSource dataSource) {
        this.dataSource = dataSource;
        template = new NamedParameterJdbcTemplate(dataSource);
    }

    public void insert(Transaction txn) {
        Map<String, Object> paramMap = new HashMap<>();
        paramMap.put("localId", txn.localId);
        paramMap.put("transactionId", txn.transactionId);
        paramMap.put("checksum", txn.checksum);
        paramMap.put("debtorAcct1", txn.debtorAcct1);
        paramMap.put("debtorAcct2", txn.debtorAcct2);
        paramMap.put("debtorAcct3", txn.debtorAcct3);
        paramMap.put("debtorAcct4", txn.debtorAcct4);
        paramMap.put("creditorAcct1", txn.creditorAcct1);
        paramMap.put("creditorAcct2", txn.creditorAcct2);
        paramMap.put("creditorAcct3", txn.creditorAcct3);
        paramMap.put("creditorAcct4", txn.creditorAcct4);
        paramMap.put("amount", txn.amount);
        paramMap.put("numeric01", txn.numeric01);
        paramMap.put("numeric02", txn.numeric02);
        paramMap.put("numeric03", txn.numeric03);
        paramMap.put("numeric04", txn.numeric04);
        paramMap.put("numeric05", txn.numeric05);
        paramMap.put("numeric06", txn.numeric06);
        paramMap.put("numeric07", txn.numeric07);
        paramMap.put("numeric08", txn.numeric08);
        paramMap.put("numeric09", txn.numeric09);
        paramMap.put("numeric10", txn.numeric10);
        paramMap.put("numeric11", txn.numeric11);
        paramMap.put("numeric12", txn.numeric12);
        paramMap.put("numeric13", txn.numeric13);
        paramMap.put("numeric14", txn.numeric14);
        paramMap.put("numeric15", txn.numeric15);
        paramMap.put("numeric16", txn.numeric16);
        paramMap.put("numeric17", txn.numeric17);
        paramMap.put("numeric18", txn.numeric18);
        paramMap.put("numeric19", txn.numeric19);
        paramMap.put("numeric20", txn.numeric20);
        paramMap.put("numeric21", txn.numeric21);
        paramMap.put("numeric22", txn.numeric22);
        paramMap.put("numeric23", txn.numeric23);
        paramMap.put("numeric24", txn.numeric24);
        paramMap.put("numeric25", txn.numeric25);
        paramMap.put("numeric26", txn.numeric26);
        paramMap.put("numeric27", txn.numeric27);
        paramMap.put("numeric28", txn.numeric28);
        paramMap.put("numeric29", txn.numeric29);
        paramMap.put("numeric30", txn.numeric30);
        paramMap.put("numeric31", txn.numeric31);
        paramMap.put("numeric32", txn.numeric32);
        paramMap.put("numeric33", txn.numeric33);
        paramMap.put("numeric34", txn.numeric34);
        paramMap.put("numeric35", txn.numeric35);
        paramMap.put("numeric36", txn.numeric36);
        paramMap.put("numeric37", txn.numeric37);
        paramMap.put("numeric38", txn.numeric38);
        paramMap.put("numeric39", txn.numeric39);
        paramMap.put("numeric40", txn.numeric40);
        paramMap.put("numeric41", txn.numeric41);
        paramMap.put("numeric42", txn.numeric42);
        paramMap.put("numeric43", txn.numeric43);
        paramMap.put("numeric44", txn.numeric44);
        paramMap.put("numeric45", txn.numeric45);
        paramMap.put("numeric46", txn.numeric46);
        paramMap.put("numeric47", txn.numeric47);
        paramMap.put("numeric48", txn.numeric48);
        paramMap.put("numeric49", txn.numeric49);
        paramMap.put("numeric50", txn.numeric50);
        paramMap.put("numeric51", txn.numeric51);
        paramMap.put("numeric52", txn.numeric52);
        paramMap.put("numeric53", txn.numeric53);
        paramMap.put("numeric54", txn.numeric54);
        paramMap.put("alphanr01", txn.alphanr01);
        paramMap.put("alphanr02", txn.alphanr02);
        paramMap.put("alphanr03", txn.alphanr03);
        paramMap.put("alphanr04", txn.alphanr04);
        paramMap.put("alphanr05", txn.alphanr05);
        paramMap.put("alphanr06", txn.alphanr06);
        paramMap.put("alphanr07", txn.alphanr07);
        paramMap.put("alphanr08", txn.alphanr08);
        paramMap.put("alphanr09", txn.alphanr09);
        paramMap.put("alphanr10", txn.alphanr10);
        paramMap.put("alphanr11", txn.alphanr11);
        paramMap.put("alphanr12", txn.alphanr12);
        paramMap.put("alphanr13", txn.alphanr13);
        paramMap.put("alphanr14", txn.alphanr14);
        paramMap.put("alphanr15", txn.alphanr15);
        paramMap.put("alphanr16", txn.alphanr16);
        paramMap.put("alphanr17", txn.alphanr17);
        paramMap.put("alphanr18", txn.alphanr18);
        paramMap.put("alphanr19", txn.alphanr19);
        paramMap.put("alphanr20", txn.alphanr20);
        paramMap.put("alphanr21", txn.alphanr21);
        paramMap.put("alphanr22", txn.alphanr22);
        paramMap.put("alphanr23", txn.alphanr23);
        paramMap.put("alphanr24", txn.alphanr24);
        paramMap.put("alphanr25", txn.alphanr25);
        paramMap.put("alphanr26", txn.alphanr26);
        paramMap.put("alphanr27", txn.alphanr27);
        paramMap.put("alphanr28", txn.alphanr28);
        paramMap.put("alphanr29", txn.alphanr29);
        paramMap.put("alphanr30", txn.alphanr30);
        paramMap.put("alphanr31", txn.alphanr31);
        paramMap.put("alphanr32", txn.alphanr32);
        paramMap.put("alphanr33", txn.alphanr33);
        paramMap.put("alphanr34", txn.alphanr34);
        paramMap.put("alphanr35", txn.alphanr35);
        paramMap.put("alphanr36", txn.alphanr36);
        paramMap.put("alphanr37", txn.alphanr37);
        paramMap.put("alphanr38", txn.alphanr38);
        paramMap.put("alphanr39", txn.alphanr39);
        paramMap.put("alphanr40", txn.alphanr40);
        paramMap.put("alphanr41", txn.alphanr41);
        paramMap.put("alphanr42", txn.alphanr42);
        paramMap.put("alphanr43", txn.alphanr43);
        paramMap.put("alphanr44", txn.alphanr44);
        paramMap.put("alphanr45", txn.alphanr45);
        paramMap.put("alphanr46", txn.alphanr46);
        paramMap.put("alphanr47", txn.alphanr47);
        paramMap.put("alphanr48", txn.alphanr48);
        paramMap.put("alphanr49", txn.alphanr49);
        paramMap.put("alphanr50", txn.alphanr50);
        paramMap.put("alphanr51", txn.alphanr51);
        paramMap.put("alphanr52", txn.alphanr52);
        paramMap.put("alphanr53", txn.alphanr53);
        paramMap.put("alphanr54", txn.alphanr54);
        paramMap.put("operationTmstmp", txn.operationTmstmp);
        paramMap.put("additionalInfo", txn.additionalInfo);
        template.update(INSERT_TRANSACTION_SQL, paramMap);
    }
}
