package ro.bb.tranzactii.repositories;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import ro.bb.tranzactii.model.Transaction;

@Mapper
public interface TransactionMyBatisRepository {

    static final String INSERT_TRANSACTION_SQL = """
                    INSERT INTO tranzactii
                    ( local_id
                    , transaction_id
                    , checksum
                    , debtor_acct1
                    , debtor_acct2
                    , debtor_acct3
                    , debtor_acct4
                    , creditor_acct1
                    , creditor_acct2
                    , creditor_acct3
                    , creditor_acct4
                    , amount
                    , numeric01
                    , numeric02
                    , numeric03
                    , numeric04
                    , numeric05
                    , numeric06
                    , numeric07
                    , numeric08
                    , numeric09
                    , numeric10
                    , numeric11
                    , numeric12
                    , numeric13
                    , numeric14
                    , numeric15
                    , numeric16
                    , numeric17
                    , numeric18
                    , numeric19
                    , numeric20
                    , numeric21
                    , numeric22
                    , numeric23
                    , numeric24
                    , numeric25
                    , numeric26
                    , numeric27
                    , numeric28
                    , numeric29
                    , numeric30
                    , numeric31
                    , numeric32
                    , numeric33
                    , numeric34
                    , numeric35
                    , numeric36
                    , numeric37
                    , numeric38
                    , numeric39
                    , numeric40
                    , numeric41
                    , numeric42
                    , numeric43
                    , numeric44
                    , numeric45
                    , numeric46
                    , numeric47
                    , numeric48
                    , numeric49
                    , numeric50
                    , numeric51
                    , numeric52
                    , numeric53
                    , numeric54
                    , alphanr01
                    , alphanr02
                    , alphanr03
                    , alphanr04
                    , alphanr05
                    , alphanr06
                    , alphanr07
                    , alphanr08
                    , alphanr09
                    , alphanr10
                    , alphanr11
                    , alphanr12
                    , alphanr13
                    , alphanr14
                    , alphanr15
                    , alphanr16
                    , alphanr17
                    , alphanr18
                    , alphanr19
                    , alphanr20
                    , alphanr21
                    , alphanr22
                    , alphanr23
                    , alphanr24
                    , alphanr25
                    , alphanr26
                    , alphanr27
                    , alphanr28
                    , alphanr29
                    , alphanr30
                    , alphanr31
                    , alphanr32
                    , alphanr33
                    , alphanr34
                    , alphanr35
                    , alphanr36
                    , alphanr37
                    , alphanr38
                    , alphanr39
                    , alphanr40
                    , alphanr41
                    , alphanr42
                    , alphanr43
                    , alphanr44
                    , alphanr45
                    , alphanr46
                    , alphanr47
                    , alphanr48
                    , alphanr49
                    , alphanr50
                    , alphanr51
                    , alphanr52
                    , alphanr53
                    , alphanr54
                    , operation_tmstmp
                    , additional_info
                    )
                    VALUES
                    ( #{localId}
                    , #{transactionId}
                    , #{checksum}
                    , #{debtorAcct1}
                    , #{debtorAcct2}
                    , #{debtorAcct3}
                    , #{debtorAcct4}
                    , #{creditorAcct1}
                    , #{creditorAcct2}
                    , #{creditorAcct3}
                    , #{creditorAcct4}
                    , #{amount}
                    , #{numeric01}
                    , #{numeric02}
                    , #{numeric03}
                    , #{numeric04}
                    , #{numeric05}
                    , #{numeric06}
                    , #{numeric07}
                    , #{numeric08}
                    , #{numeric09}
                    , #{numeric10}
                    , #{numeric11}
                    , #{numeric12}
                    , #{numeric13}
                    , #{numeric14}
                    , #{numeric15}
                    , #{numeric16}
                    , #{numeric17}
                    , #{numeric18}
                    , #{numeric19}
                    , #{numeric20}
                    , #{numeric21}
                    , #{numeric22}
                    , #{numeric23}
                    , #{numeric24}
                    , #{numeric25}
                    , #{numeric26}
                    , #{numeric27}
                    , #{numeric28}
                    , #{numeric29}
                    , #{numeric30}
                    , #{numeric31}
                    , #{numeric32}
                    , #{numeric33}
                    , #{numeric34}
                    , #{numeric35}
                    , #{numeric36}
                    , #{numeric37}
                    , #{numeric38}
                    , #{numeric39}
                    , #{numeric40}
                    , #{numeric41}
                    , #{numeric42}
                    , #{numeric43}
                    , #{numeric44}
                    , #{numeric45}
                    , #{numeric46}
                    , #{numeric47}
                    , #{numeric48}
                    , #{numeric49}
                    , #{numeric50}
                    , #{numeric51}
                    , #{numeric52}
                    , #{numeric53}
                    , #{numeric54}
                    , #{alphanr01}
                    , #{alphanr02}
                    , #{alphanr03}
                    , #{alphanr04}
                    , #{alphanr05}
                    , #{alphanr06}
                    , #{alphanr07}
                    , #{alphanr08}
                    , #{alphanr09}
                    , #{alphanr10}
                    , #{alphanr11}
                    , #{alphanr12}
                    , #{alphanr13}
                    , #{alphanr14}
                    , #{alphanr15}
                    , #{alphanr16}
                    , #{alphanr17}
                    , #{alphanr18}
                    , #{alphanr19}
                    , #{alphanr20}
                    , #{alphanr21}
                    , #{alphanr22}
                    , #{alphanr23}
                    , #{alphanr24}
                    , #{alphanr25}
                    , #{alphanr26}
                    , #{alphanr27}
                    , #{alphanr28}
                    , #{alphanr29}
                    , #{alphanr30}
                    , #{alphanr31}
                    , #{alphanr32}
                    , #{alphanr33}
                    , #{alphanr34}
                    , #{alphanr35}
                    , #{alphanr36}
                    , #{alphanr37}
                    , #{alphanr38}
                    , #{alphanr39}
                    , #{alphanr40}
                    , #{alphanr41}
                    , #{alphanr42}
                    , #{alphanr43}
                    , #{alphanr44}
                    , #{alphanr45}
                    , #{alphanr46}
                    , #{alphanr47}
                    , #{alphanr48}
                    , #{alphanr49}
                    , #{alphanr50}
                    , #{alphanr51}
                    , #{alphanr52}
                    , #{alphanr53}
                    , #{alphanr54}
                    , #{operationTmstmp}
                    , #{additionalInfo}
                    )
            """;

    @Insert(INSERT_TRANSACTION_SQL)
//    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    void insert(Transaction transaction);


}
