package ro.bb.tranzactii.repositories;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import ro.bb.tranzactii.model.Transaction;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

@Repository
public class TransactionOneStatementRepository {

    private static final String INSERT_TRANSACTION_SQL = """
            INSERT INTO tranzactii
            ( local_id
            , transaction_id
            , checksum
            , debtor_acct1
            , debtor_acct2
            , debtor_acct3
            , debtor_acct4
            , creditor_acct1
            , creditor_acct2
            , creditor_acct3
            , creditor_acct4
            , amount
            , numeric01
            , numeric02
            , numeric03
            , numeric04
            , numeric05
            , numeric06
            , numeric07
            , numeric08
            , numeric09
            , numeric10
            , numeric11
            , numeric12
            , numeric13
            , numeric14
            , numeric15
            , numeric16
            , numeric17
            , numeric18
            , numeric19
            , numeric20
            , numeric21
            , numeric22
            , numeric23
            , numeric24
            , numeric25
            , numeric26
            , numeric27
            , numeric28
            , numeric29
            , numeric30
            , numeric31
            , numeric32
            , numeric33
            , numeric34
            , numeric35
            , numeric36
            , numeric37
            , numeric38
            , numeric39
            , numeric40
            , numeric41
            , numeric42
            , numeric43
            , numeric44
            , numeric45
            , numeric46
            , numeric47
            , numeric48
            , numeric49
            , numeric50
            , numeric51
            , numeric52
            , numeric53
            , numeric54
            , alphanr01
            , alphanr02
            , alphanr03
            , alphanr04
            , alphanr05
            , alphanr06
            , alphanr07
            , alphanr08
            , alphanr09
            , alphanr10
            , alphanr11
            , alphanr12
            , alphanr13
            , alphanr14
            , alphanr15
            , alphanr16
            , alphanr17
            , alphanr18
            , alphanr19
            , alphanr20
            , alphanr21
            , alphanr22
            , alphanr23
            , alphanr24
            , alphanr25
            , alphanr26
            , alphanr27
            , alphanr28
            , alphanr29
            , alphanr30
            , alphanr31
            , alphanr32
            , alphanr33
            , alphanr34
            , alphanr35
            , alphanr36
            , alphanr37
            , alphanr38
            , alphanr39
            , alphanr40
            , alphanr41
            , alphanr42
            , alphanr43
            , alphanr44
            , alphanr45
            , alphanr46
            , alphanr47
            , alphanr48
            , alphanr49
            , alphanr50
            , alphanr51
            , alphanr52
            , alphanr53
            , alphanr54
            , operation_tmstmp
            , additional_info
            )
            VALUES
            ( ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            , ?
            )
                        """;

    DataSource dataSource;
    PreparedStatement preparedStatement;

    @Autowired
    public TransactionOneStatementRepository(DataSource dataSource) {
        this.dataSource = dataSource;
        try {
            Connection connection = dataSource.getConnection();
            preparedStatement = connection.prepareStatement(INSERT_TRANSACTION_SQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void insert(Transaction txn) throws SQLException {
        /* TODO de exploatat in mod inteligent parametrii din instructiunea named-parameter
        Map<String, Object> paramMap = new HashMap<>();
        paramMap.put("localId", txn.localId);
        paramMap.put("transactionId", txn.transactionId);
        paramMap.put("checksum", txn.checksum);
        paramMap.put("debtorAcct1", txn.debtorAcct1);
        paramMap.put("debtorAcct2", txn.debtorAcct2);
        paramMap.put("debtorAcct3", txn.debtorAcct3);
        paramMap.put("debtorAcct4", txn.debtorAcct4);
        paramMap.put("creditorAcct1", txn.creditorAcct1);
        paramMap.put("creditorAcct2", txn.creditorAcct2);
        paramMap.put("creditorAcct3", txn.creditorAcct3);
        paramMap.put("creditorAcct4", txn.creditorAcct4);
        paramMap.put("amount", txn.amount);
        paramMap.put("operationTmstmp", txn.operationTmstmp);
        paramMap.put("additionalInfo", txn.additionalInfo);
        */
        int iParam = 0;
        preparedStatement.setLong(++iParam, txn.localId);
        preparedStatement.setString(++iParam, txn.transactionId);
        preparedStatement.setLong(++iParam, txn.checksum);
        preparedStatement.setString(++iParam, txn.debtorAcct1);
        preparedStatement.setString(++iParam, txn.debtorAcct2);
        preparedStatement.setString(++iParam, txn.debtorAcct3);
        preparedStatement.setString(++iParam, txn.debtorAcct4);
        preparedStatement.setString(++iParam, txn.creditorAcct1);
        preparedStatement.setString(++iParam, txn.creditorAcct2);
        preparedStatement.setString(++iParam, txn.creditorAcct3);
        preparedStatement.setString(++iParam, txn.creditorAcct4);
        preparedStatement.setBigDecimal(++iParam, txn.amount);
        preparedStatement.setLong(++iParam, txn.numeric01);
        preparedStatement.setLong(++iParam, txn.numeric02);
        preparedStatement.setLong(++iParam, txn.numeric03);
        preparedStatement.setLong(++iParam, txn.numeric04);
        preparedStatement.setLong(++iParam, txn.numeric05);
        preparedStatement.setLong(++iParam, txn.numeric06);
        preparedStatement.setLong(++iParam, txn.numeric07);
        preparedStatement.setLong(++iParam, txn.numeric08);
        preparedStatement.setLong(++iParam, txn.numeric09);
        preparedStatement.setLong(++iParam, txn.numeric10);
        preparedStatement.setLong(++iParam, txn.numeric11);
        preparedStatement.setLong(++iParam, txn.numeric12);
        preparedStatement.setLong(++iParam, txn.numeric13);
        preparedStatement.setLong(++iParam, txn.numeric14);
        preparedStatement.setLong(++iParam, txn.numeric15);
        preparedStatement.setLong(++iParam, txn.numeric16);
        preparedStatement.setLong(++iParam, txn.numeric17);
        preparedStatement.setLong(++iParam, txn.numeric18);
        preparedStatement.setLong(++iParam, txn.numeric19);
        preparedStatement.setLong(++iParam, txn.numeric20);
        preparedStatement.setLong(++iParam, txn.numeric21);
        preparedStatement.setLong(++iParam, txn.numeric22);
        preparedStatement.setLong(++iParam, txn.numeric23);
        preparedStatement.setLong(++iParam, txn.numeric24);
        preparedStatement.setLong(++iParam, txn.numeric25);
        preparedStatement.setLong(++iParam, txn.numeric26);
        preparedStatement.setLong(++iParam, txn.numeric27);
        preparedStatement.setLong(++iParam, txn.numeric28);
        preparedStatement.setLong(++iParam, txn.numeric29);
        preparedStatement.setLong(++iParam, txn.numeric30);
        preparedStatement.setLong(++iParam, txn.numeric31);
        preparedStatement.setLong(++iParam, txn.numeric32);
        preparedStatement.setLong(++iParam, txn.numeric33);
        preparedStatement.setLong(++iParam, txn.numeric34);
        preparedStatement.setLong(++iParam, txn.numeric35);
        preparedStatement.setLong(++iParam, txn.numeric36);
        preparedStatement.setLong(++iParam, txn.numeric37);
        preparedStatement.setLong(++iParam, txn.numeric38);
        preparedStatement.setLong(++iParam, txn.numeric39);
        preparedStatement.setLong(++iParam, txn.numeric40);
        preparedStatement.setLong(++iParam, txn.numeric41);
        preparedStatement.setLong(++iParam, txn.numeric42);
        preparedStatement.setLong(++iParam, txn.numeric43);
        preparedStatement.setLong(++iParam, txn.numeric44);
        preparedStatement.setLong(++iParam, txn.numeric45);
        preparedStatement.setLong(++iParam, txn.numeric46);
        preparedStatement.setLong(++iParam, txn.numeric47);
        preparedStatement.setLong(++iParam, txn.numeric48);
        preparedStatement.setLong(++iParam, txn.numeric49);
        preparedStatement.setLong(++iParam, txn.numeric50);
        preparedStatement.setLong(++iParam, txn.numeric51);
        preparedStatement.setLong(++iParam, txn.numeric52);
        preparedStatement.setLong(++iParam, txn.numeric53);
        preparedStatement.setLong(++iParam, txn.numeric54);
        preparedStatement.setString(++iParam, txn.alphanr01);
        preparedStatement.setString(++iParam, txn.alphanr02);
        preparedStatement.setString(++iParam, txn.alphanr03);
        preparedStatement.setString(++iParam, txn.alphanr04);
        preparedStatement.setString(++iParam, txn.alphanr05);
        preparedStatement.setString(++iParam, txn.alphanr06);
        preparedStatement.setString(++iParam, txn.alphanr07);
        preparedStatement.setString(++iParam, txn.alphanr08);
        preparedStatement.setString(++iParam, txn.alphanr09);
        preparedStatement.setString(++iParam, txn.alphanr10);
        preparedStatement.setString(++iParam, txn.alphanr11);
        preparedStatement.setString(++iParam, txn.alphanr12);
        preparedStatement.setString(++iParam, txn.alphanr13);
        preparedStatement.setString(++iParam, txn.alphanr14);
        preparedStatement.setString(++iParam, txn.alphanr15);
        preparedStatement.setString(++iParam, txn.alphanr16);
        preparedStatement.setString(++iParam, txn.alphanr17);
        preparedStatement.setString(++iParam, txn.alphanr18);
        preparedStatement.setString(++iParam, txn.alphanr19);
        preparedStatement.setString(++iParam, txn.alphanr20);
        preparedStatement.setString(++iParam, txn.alphanr21);
        preparedStatement.setString(++iParam, txn.alphanr22);
        preparedStatement.setString(++iParam, txn.alphanr23);
        preparedStatement.setString(++iParam, txn.alphanr24);
        preparedStatement.setString(++iParam, txn.alphanr25);
        preparedStatement.setString(++iParam, txn.alphanr26);
        preparedStatement.setString(++iParam, txn.alphanr27);
        preparedStatement.setString(++iParam, txn.alphanr28);
        preparedStatement.setString(++iParam, txn.alphanr29);
        preparedStatement.setString(++iParam, txn.alphanr30);
        preparedStatement.setString(++iParam, txn.alphanr31);
        preparedStatement.setString(++iParam, txn.alphanr32);
        preparedStatement.setString(++iParam, txn.alphanr33);
        preparedStatement.setString(++iParam, txn.alphanr34);
        preparedStatement.setString(++iParam, txn.alphanr35);
        preparedStatement.setString(++iParam, txn.alphanr36);
        preparedStatement.setString(++iParam, txn.alphanr37);
        preparedStatement.setString(++iParam, txn.alphanr38);
        preparedStatement.setString(++iParam, txn.alphanr39);
        preparedStatement.setString(++iParam, txn.alphanr40);
        preparedStatement.setString(++iParam, txn.alphanr41);
        preparedStatement.setString(++iParam, txn.alphanr42);
        preparedStatement.setString(++iParam, txn.alphanr43);
        preparedStatement.setString(++iParam, txn.alphanr44);
        preparedStatement.setString(++iParam, txn.alphanr45);
        preparedStatement.setString(++iParam, txn.alphanr46);
        preparedStatement.setString(++iParam, txn.alphanr47);
        preparedStatement.setString(++iParam, txn.alphanr48);
        preparedStatement.setString(++iParam, txn.alphanr49);
        preparedStatement.setString(++iParam, txn.alphanr50);
        preparedStatement.setString(++iParam, txn.alphanr51);
        preparedStatement.setString(++iParam, txn.alphanr52);
        preparedStatement.setString(++iParam, txn.alphanr53);
        preparedStatement.setString(++iParam, txn.alphanr54);
        //preparedStatement.setTimestamp(13, new Timestamp(txn.operationTmstmp.toInstant().toEpochMilli()));
        preparedStatement.setObject(++iParam, txn.operationTmstmp);  // s-o descurca?
        preparedStatement.setString(++iParam, txn.additionalInfo);
        preparedStatement.executeUpdate();
    }
}
